//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_VENDOR_TRANSACTION
    {
        #region Primitive Properties
    
        public virtual string PONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<int> VersionPOSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DataVersion
        {
            get;
            set;
        }
    
        public virtual string StatusPOSERA
        {
            get;
            set;
        }
    
        public virtual string RejectRevisedPOSERA
        {
            get;
            set;
        }
    
        public virtual string DocumentNo
        {
            get;
            set;
        }
    
        public virtual string AIMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialDescription
        {
            get;
            set;
        }
    
        public virtual string AIColor
        {
            get;
            set;
        }
    
        public virtual string SERAColor
        {
            get;
            set;
        }
    
        public virtual string QuotationNo
        {
            get;
            set;
        }
    
        public virtual string SalesOrderNo
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SalesOrderStatus
        {
            get;
            set;
        }
    
        public virtual string Currency
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Year
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> BillingStatus
        {
            get;
            set;
        }
    
        public virtual string CancellationReason
        {
            get;
            set;
        }
    
        public virtual string BSTKBNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RevisiSTNK
        {
            get;
            set;
        }
    
        public virtual string NamaPenerima
        {
            get;
            set;
        }
    
        public virtual string AlamatPenerima
        {
            get;
            set;
        }
    
        public virtual string StatusCancel
        {
            get;
            set;
        }
    
        public virtual string ReasonRejection
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> AmountKuitansiDC
        {
            get;
            set;
        }
    
        public virtual string BusinessAreaCode
        {
            get;
            set;
        }
    
        public virtual string CustomerNo
        {
            get;
            set;
        }
    
        public virtual string NomorSpes
        {
            get;
            set;
        }
    
        public virtual string SalesmanNumber
        {
            get;
            set;
        }
    
        public virtual string KuitansiNoRef
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> KuitansiDateRef
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DownloadDate
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual string ModifiedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
